### ISSUE TITLE
[Feature Request] Mixtral Model Support

### ISSUE THREAD

**Issue by birdup000** [lyogavin/Anima#79]
Trying to load the Mistral model but is having issue loading. I've tried the example one you had for the Platypus model and it loaded correctly, the Mistral model is having an issue. 

```python
from airllm import AirLLMMistral

MAX_LENGTH = 128
# could use hugging face model repo id:
model = AirLLMMistral("mistralai/Mixtral-8x7B-v0.1",
                     compression='4bit' # specify '8bit' for 8-bit block-wise quantization 
                    )


# or use model's local path...
#model = AirLLMLlama2("/home/ubuntu/.cache/huggingface/hub/models--garage-bAInd--Platypus2-70B-instruct/snapshots/b585e74bcaae02e52665d9ac6d23f4d0dbc81a0f")

input_text = [
        'how to build a computer?',
        #'I like',
    ]

input_tokens = model.tokenizer(input_text,
    return_tensors="pt", 
    return_attention_mask=False, 
    truncation=True, 
    max_length=MAX_LENGTH, 
    padding=False)
           
generation_output = model.generate(
    input_tokens['input_ids'].cuda(), 
    max_new_tokens=50,
    use_cache=True,
    return_dict_in_generate=True)

output = model.tokenizer.decode(generation_output.sequences[0])

print(output)
```

error message with 4-bit  quantization

```
raceback (most recent call last):
  File "/mnt/aedc235c-d458-41cb-88fa-1da70ef3b1bc/AirLLM/myAI.py", line 25, in <module>
    generation_output = model.generate(
  File "/home/bird/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/bird/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1718, in generate
    return self.greedy_search(
  File "/home/bird/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2579, in greedy_search
    outputs = self(
  File "/home/bird/.local/lib/python3.10/site-packages/airllm/airllm_mistral.py", line 194, in __call__
    return self.forward(*args, **kwargs)
  File "/home/bird/.local/lib/python3.10/site-packages/airllm/airllm_mistral.py", line 258, in forward
    self.move_layer_to_device(state_dict)
  File "/home/bird/.local/lib/python3.10/site-packages/airllm/airllm_mistral.py", line 147, in move_layer_to_device
    set_module_tensor_to_device(self.model, param_name, self.running_device, value=param,
  File "/home/bird/.local/lib/python3.10/site-packages/accelerate/utils/modeling.py", line 293, in set_module_tensor_to_device
    value = value.to(dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 112.00 MiB. GPU 0 has a total capacty of 5.78 GiB of which 90.81 MiB is free. Including non-PyTorch memory, this process has 4.99 GiB memory in use. Of the allocated memory 4.73 GiB is allocated by PyTorch, and 167.60 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

**Comment by birdup000** [comment]
I try with no quantization

```
Traceback (most recent call last):
  File "/mnt/aedc235c-d458-41cb-88fa-1da70ef3b1bc/AirLLM/myAI.py", line 23, in <module>
    generation_output = model.generate(
  File "/home/bird/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/bird/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 1718, in generate
    return self.greedy_search(
  File "/home/bird/.local/lib/python3.10/site-packages/transformers/generation/utils.py", line 2579, in greedy_search
    outputs = self(
  File "/home/bird/.local/lib/python3.10/site-packages/airllm/airllm_mistral.py", line 194, in __call__
    return self.forward(*args, **kwargs)
  File "/home/bird/.local/lib/python3.10/site-packages/airllm/airllm_mistral.py", line 327, in forward
    new_seq, (k_cache, v_cache) = layer(seq,
TypeError: cannot unpack non-iterable NoneType object
```

**Comment by Josh-XT** [comment]
![image](https://github.com/lyogavin/Anima/assets/102809327/a4869748-429c-474e-983b-76e59caae026)

This is what I got when I tried.

**Comment by lyogavin** [comment]
Yes. It's the latest upgrade of transformer has some breaking changes.

I'll fix it today.

**Comment by lyogavin** [comment]
I think it's fixed in 3d59aad1b95670ec4dd6a37d3c2a8b74983ee3b5.

I tested it here, it works now:
 <a target="_blank" href="https://colab.research.google.com/github/lyogavin/Anima/blob/main/air_llm/examples/run_all_types_of_models.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a> 

Feel free to reopen if you still have problem your end.

**Comment by birdup000** [comment]
@lyogavin 
Did it work with the Mixtral model from Mistral ?

**Comment by lyogavin** [comment]
ehmm. let me try.

**Comment by birdup000** [comment]
> ehmm. let me try.

It's this model https://huggingface.co/mistralai/Mixtral-8x7B-v0.1

**Comment by lyogavin** [comment]
fixed in d2182a1bf6d73c171d8f8ed6bf4047323c4c609e

airllm==2.7

**Comment by lyogavin** [comment]
test: https://github.com/lyogavin/Anima/blob/main/air_llm/tests/test_notebooks/test_mixtral.ipynb

**Comment by lyogavin** [comment]
feel free to reopen

**Comment by birdup000** [comment]
Thank you so much for adding I'll try in a bit.
